# Generated by Django 5.0 on 2025-04-20 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptedNote',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('salt', models.TextField()),
                ('iv', models.TextField()),
                ('ciphertext', models.TextField()),
                ('tag', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
